### ISSUE TITLE
Promblem with connection

### ISSUE THREAD

**Issue by Flavoredone** [EspecNorthAmerica/ChamberConnectLibrary#18]
Hi! It seems that to connect I need to log in to the client, how can this be done in the console? The error [Errno 10061] appears when connecting.  The firewall is disabled, the hosts are the same. The client opens in the browser. 

Thank you in advance

**Comment by Flavoredone** [comment]
![image](https://user-images.githubusercontent.com/68301720/145799568-3ae88f11-6bf5-48f9-bf72-8ee4dfa3a670.jpeg)

![image](https://user-images.githubusercontent.com/68301720/145799615-8652e2f6-87b9-4f3a-ae8a-5a47c9cea7ae.jpeg)

**Comment by Flavoredone** [comment]
![image](https://user-images.githubusercontent.com/68301720/145799691-c3962abd-ebff-4dbd-8f42-ac6cba2db72e.jpeg)
![image](https://user-images.githubusercontent.com/68301720/145799838-1653e445-a3ed-4a25-b66e-faba3131e4ed.jpeg)

**Comment by Flavoredone** [comment]
@HallEffect Привет, можешь помочь пожалуйста, буду очень благодарен

**Comment by MylesMetzler** [comment]
The device you sent a screenshot from is not an officially supported controller type, if it is a P310/P200/P100 it will likely work by changing the tcp port to 57732.

Example connecting to a P200:
```python
from chamberconnectlibrary.especp300 import EspecP300

p200 = EspecP300(interface="TCP", host="10.30.200.249", port=57732)
print p200.process_controller(True) # this will correctly configure the class even though it says its connected to a P300
```

`port`, and `address` must be an integer, `delimeter` must be `'\r\n'` in the case of a P310/P200/P100. I have no idea where '335' would come from.

**Comment by Flavoredone** [comment]
Hi, I'm sorry that I often distract you, but it still doesn't work out. I tried to connect via `port = 57732`, all the same errors are generated anyway. I'm trying to connect to the gmc-71 (chineese but espec) chamber, the controller is most likely p310. And there is also no `EspecP300` in the `chamberconnectlibrary`. Are there any other ways to run it? And thank you in advance.

**Comment by Flavoredone** [comment]
```
from chamberconnectlibrary.espec import Espec

CONTROLLER = Espec(ctlr_type='P300', loops=1, interface='TCP', host='192.168.100.60', port=57732)

print(CONTROLLER.process_controller(True))
```

And the same error:
```
 File "C:\Users\rafae\Desktop\espec gui\venv\lib\site-packages\chamberconnectlibrary\especinteract.py", line 119, in __init__
    self.socket.connect((kwargs.get('host'), kwargs.get('port', 10001)))
  File "C:\Python27\lib\socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
socket.error: [Errno 10061] ����������� �� �����������,
```

**Comment by MylesMetzler** [comment]
You will likely need to contact espec china or who ever provided the unit about this. This unit does not have a P310 (it looks like a P100 or P200) in it. In some meetings a few years ago they where discussing making there own controller that looks very much like a P100 so I'm not sure I can help.

This library was intended for North America units, and it does work on Japanese made units too. I do not have access to the units produced in China.
