### ISSUE TITLE
pip command for 3.6.8 not working

### ISSUE THREAD

**Issue by LeandroBorgesHT** [EspecNorthAmerica/ChamberConnectLibrary#21]
I tried using pip install chamberconnectlibrary-3.6.8 and got this message:

ERROR: Could not find a version that satisfies the requirement chamberconnectlibrary-3.6.8 (from versions: none)
ERROR: No matching distribution found for chamberconnectlibrary-3.6.8

I'm using python 3.9.4 and pip 22.3.1

Does anyone know if there's a problem?

**Comment by MylesMetzler** [comment]
It looks like the python3 version has not been pushed to pypi. Until that happens you may use (as long as you also have git installed):

`pip install git+https://github.com/EspecNorthAmerica/ChamberConnectLibrary.git@py3-chamberconnectlibrary`

or 

`pip3 install git+https://github.com/EspecNorthAmerica/ChamberConnectLibrary.git@py3-chamberconnectlibrary`

**Comment by LeandroBorgesHT** [comment]
> It looks like the python3 version has not been pushed to pypi. Until that happens you may use (as long as you also have git installed):
> 
> `pip install git+https://github.com/EspecNorthAmerica/ChamberConnectLibrary.git@py3-chamberconnectlibrary`
> 
> or
> 
> `pip3 install git+https://github.com/EspecNorthAmerica/ChamberConnectLibrary.git@py3-chamberconnectlibrary`

Thank you very much, it worked properly.

**Comment by PaulNongL** [comment]
Any Python3 version on or above 3.6.8 will work with the chamberconnectlibrary-3.6.8, but it PYPI has not been completely pushed. In the meantime, you may still use it; simply pull and use it directly in the directory. The complete PYPI will be pushed soon.

**Comment by PaulNongL** [comment]
> I tried using pip install chamberconnectlibrary-3.6.8 and got this message:
> 
> ERROR: Could not find a version that satisfies the requirement chamberconnectlibrary-3.6.8 (from versions: none) ERROR: No matching distribution found for chamberconnectlibrary-3.6.8
> 
> I'm using python 3.9.4 and pip 22.3.1
> 
> Does anyone know if there's a problem?

Any Python3 version on or above 3.6.8 will work with the chamberconnectlibrary-3.6.8, but it PYPI has not been completely pushed. In the meantime, you may still use it; simply pull and use it directly in the directory. The complete PYPI will be pushed soon.
