### ISSUE TITLE
Wrong file names in chamberconnectlibrary-2.0.2.tar.gz on https://pypi.python.org

### ISSUE THREAD

**Issue by HallEffect** [EspecNorthAmerica/ChamberConnectLibrary#3]
In `chamberconnectlibrary-2.0.2.tar.gz` from https://pypi.python.org files are named in CamelCase style: `WatlowF4T.py`, `P300.py`, `EspecInteract.py`

Because of that, there are some import errors, for example in `espec.py`:
```
from chamberconnectlibrary.p300 import P300
...
from chamberconnectlibrary.especinteract import EspecError
```

In repo on github these files have correct names.

Please repack tar.gz and upload it on https://pypi.python.org

**Comment by MylesMetzler** [comment]
It should be fixed with version 2.1.4

**Comment by HallEffect** [comment]
@MylesMetzler , thanks for answer. When are you going to release the next version?

**Comment by MylesMetzler** [comment]
I released it just prior to closing this issue: https://pypi.python.org/pypi/chamberconnectlibrary
When I was checking it I did have to clear pip's cache to get it to install the new version.
